#!/usr/bin/python
import sys
import subprocess
import difflib
import argparse
import os
import shutil

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--exe", required=True, help="Path to C++ executable")
    parser.add_argument("--args", default="", help="Arguments for the C++ app")
    parser.add_argument("--actual", default="NoSpherA2.log", help="Path to the log file generated by C++")
    parser.add_argument("--good", required=True, help="Path to the expected output file")
    parser.add_argument("--dir", required=True, help="Path to working dir")
    args = parser.parse_args()
    os.chdir(args.dir)
    debugging = "TEST_DEBUG" in os.environ
    print(debugging)
    args.args = [i.replace('\"', '') for i in args.args.split()] + ["-all_charges"]
    print(f"Running: {args.exe} {args.args}")

    try:
        subprocess.run(
            [args.exe] + args.args,
            check=True,
            text=True
        )
    except subprocess.CalledProcessError as e:
        if not debugging:
            print("❌ Execution failed")
            print("Stderr:", e.stderr)
        sys.exit(1)

    args_actual = args.good
    if args.actual == "NoSpherA2.log":
        args_actual = args.good.replace("good", "log")
        shutil.move(args.actual, args_actual)

    if not os.path.exists(args_actual):
        print(f"❌ Error: Output log '{args_actual}' was not created.")
        sys.exit(1)

    with open(args.good, 'r') as f:
        expected = f.readlines()

    with open(args_actual, 'r') as f:
        actual = f.readlines()

    diff = list(difflib.unified_diff(
        expected,
        actual,
        fromfile='Expected',
        tofile='Actual',
        lineterm=''
    ))

    if diff:
        print("❌ Output Mismatch!")
        for line in diff:
            if line.startswith('+'):
                print(f"\033[92m{line}\033[0m", end='') # Green
            elif line.startswith('-'):
                print(f"\033[91m{line}\033[0m", end='') # Red
            else:
                print(line, end='')
        sys.exit(1)

    print("✅ Test Passed")
    sys.exit(0)

if __name__ == "__main__":
    main()
