name: 'Cache Dependencies'
description: 'Cache platform-specific dependencies'
inputs:
  platform:
    description: 'Target platform'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Cache occ
      uses: actions/cache@v4.2.4
      with:
        path: Lib/occ
        key: ${{ inputs.platform }}-occ-${{ hashFiles('occ/**', 'makefile') }}

    - name: Cache featomic (Linux / Windows)
      if: inputs.platform == 'Linux' || inputs.platform == 'Windows'
      uses: actions/cache@v4.2.4
      with:
        path: Lib/featomic_install
        key: ${{ inputs.platform }}-featomic-${{ hashFiles('featomic/**') }}

    - name: Cache featomic (macOS ARM64)
      if: inputs.platform == 'Mac_ARM64'
      uses: actions/cache@v4.2.4
      with:
        path: Lib/featomic_install_arm64
        key: ${{ inputs.platform }}-featomic-${{ hashFiles('featomic/**') }}

    - name: Cache featomic (macOS x86_64)
      if: inputs.platform == 'Mac_x86_64'
      uses: actions/cache@v4.2.4
      with:
        path: Lib/featomic_install_x86_64
        key: ${{ inputs.platform }}-featomic-${{ hashFiles('featomic/**') }}

    - name: Cache LibCint (Linux / Windows)
      if: inputs.platform == 'Linux' || inputs.platform == 'Windows'
      uses: actions/cache@v4.2.4
      with:
        path: Lib/LibCint
        key: ${{ inputs.platform }}-libcint-${{ hashFiles('libcint/**', 'makefile') }}

    - name: Cache LibCint (macOS ARM64)
      if: inputs.platform == 'Mac_ARM64'
      uses: actions/cache@v4.2.4
      with:
        path: Lib/LibCint_arm64
        key: ${{ inputs.platform }}-libcint-${{ hashFiles('libcint/**', 'makefile') }}

    - name: Cache LibCint (macOS x86_64)
      if: inputs.platform == 'Mac_x86_64'
      uses: actions/cache@v4.2.4
      with:
        path: Lib/LibCint_x86_64
        key: ${{ inputs.platform }}-libcint-${{ hashFiles('libcint/**', 'makefile') }}

    - name: Cache MKL (Linux)
      if: inputs.platform == 'Linux'
      uses: actions/cache@v4.2.4
      with:
        path: Lib/MKL
        key: ${{ inputs.platform }}-mkl-${{ hashFiles('Lib/MKL/**') }}
        restore-keys: ${{ inputs.platform }}-mkl-

    - name: Cache MKL (Windows)
      if: inputs.platform == 'Windows'
      uses: actions/cache@v4.2.4
      with:
        path: |
          Windows\MKL.auto.props
          Windows\packages_mkl
        key: ${{ inputs.platform }}-mkl-${{ hashFiles('Lib/MKL/**') }}
        restore-keys: ${{ inputs.platform }}-mkl-