name: 'Cache Dependencies'
description: 'Cache platform-specific dependencies'
inputs:
  platform:
    description: 'Target platform'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache Dependencys (Linux)
      if: inputs.platform == 'Linux'
      uses: actions/cache@v4.2.4
      with:
        path: |
          Lib/featomic_install
          Lib/LibCint
          Lib/MKL
        key: linux-deps-${{ inputs.platform }}-${{ runner.os }}-${{ hashFiles('featomic/**') }}
        restore-keys: |
          linux-deps-${{ inputs.platform }}-

    - name: Cache Dependencys (Windows)
      if:  inputs.platform == 'Windows'
      uses: actions/cache@v4.2.4
      with:
        path: |
          Lib/featomic_install
          Windows\MKL.auto.props
          Windows\packages_mkl
          Lib/LibCint
        key: windows-deps-${{ inputs.platform }}-${{ runner.os }}-${{ hashFiles('featomic/**') }}
        restore-keys: |
          windows-deps-${{ inputs.platform }}-

    - name: Cache Dependencys (macOS ARM64)
      if: inputs.platform == 'Mac_ARM64'
      uses: actions/cache@v4.2.4
      with:
        path: |
          Lib/featomic_install_arm64
          Lib/LibCint_arm64
        key: macos-arm64-deps-${{ runner.os }}-${{ hashFiles('featomic/**') }}
        restore-keys: |
          macos-arm64-deps-${{ runner.os }}-

    - name: Cache Dependencys (macOS x86_64)
      if: inputs.platform == 'Mac_x86_64'
      uses: actions/cache@v4.2.4
      with:
        path: |
          Lib/featomic_install_x86_64
          Lib/LibCint_x86_64
        key: macos-x86_64-deps-${{ runner.os }}-${{ hashFiles('featomic/**') }}
        restore-keys: |
          macos-x86_64-deps-${{ runner.os }}-