name: 'Build Dependencies'
description: 'Build platform-specific dependencies'
inputs:
  platform:
    description: 'Target platform'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Cargo environment (Unix)
      if: inputs.platform != 'Windows'
      shell: bash
      run: |
        # Ensure cargo is in PATH and verify version
        source ~/.cargo/env || true
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
        
        # Verify we have the right version
        cargo --version
        rustc --version

    - name: Setup Cargo environment (Windows)
      if: inputs.platform == 'Windows'
      shell: powershell
      run: |
        # Ensure cargo is in PATH
        $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
        
        # Verify we have the right version
        & "$env:USERPROFILE\.cargo\bin\cargo.exe" --version
        & "$env:USERPROFILE\.cargo\bin\rustc.exe" --version

    - name: Build dependencies (Windows)
      if: inputs.platform == 'Windows'
      shell: powershell
      run: |
        # Ensure cargo is in PATH
        $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
