name: 'Build Dependencies'
description: 'Build platform-specific dependencies'
inputs:
  platform:
    description: 'Target platform'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Cargo environment (Unix)
      if: inputs.platform != 'Windows'
      shell: bash
      run: |
        # Ensure cargo is in PATH and verify version
        source ~/.cargo/env || true
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
        
        # Verify we have the right version
        cargo --version
        rustc --version

    - name: Setup Cargo environment (Windows)
      if: inputs.platform == 'Windows'
      shell: powershell
      run: |
        # Ensure cargo is in PATH
        $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
        
        # Verify we have the right version
        & "$env:USERPROFILE\.cargo\bin\cargo.exe" --version
        & "$env:USERPROFILE\.cargo\bin\rustc.exe" --version

    - name: Build featomic (Unix)
      if: inputs.platform != 'Windows'
      shell: bash
      run: |
        source ~/.cargo/env
        export PATH="$HOME/.cargo/bin:$PATH"
    
        if [ ! -f Lib/featomic_install/lib/libfeatomic.a ]; then
          echo "Building featomic for ${{ inputs.platform }}"
          cd featomic/featomic
          mkdir -p build
          cd build
          cmake ${{ env.FEATOMIC_CMAKE_FLAGS }} -DCMAKE_INSTALL_PREFIX=../../../Lib/featomic_install ..
          make install
        else
          echo 'Skipping featomic build, already exists'
        fi

    - name: Build Intel MKL (Linux)
      if: inputs.platform == 'Linux'
      shell: bash
      run: |
        if [ ! -f Lib/MKL/mkl/2025.2/lib/libmkl_core.a ]; then
          wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/47c7d946-fca1-441a-b0df-b094e3f045ea/intel-onemkl-2025.2.0.629_offline.sh
          sh intel-onemkl-2025.2.0.629_offline.sh -a -s --install-dir=${{ github.workspace }}/Lib/MKL --eula accept
        else
          echo 'Skipping IntelMKL build, already exists'
        fi

    - name: Set LD_LIBRARY_PATH for Intel OpenMP (Linux)
      if: inputs.platform == 'Linux'
      shell: bash
      run: echo "LD_LIBRARY_PATH=${{ github.workspace }}/Lib/MKL/compiler/2025.2/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Build dependencies (Windows)
      if: inputs.platform == 'Windows'
      shell: powershell
      run: |
        # Ensure cargo is in PATH
        $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
        
        # Download and install Intel oneAPI MKL for Windows
        $mklInstallDir = "${{ github.workspace }}\Lib\MKL"
        if (-not (Test-Path "$mklInstallDir\mkl\latest\lib\cmake\mkl\MKLConfig.cmake")) {
          Write-Host "Installing Intel oneAPI MKL..."
          
          # Download the online installer
          $mklInstaller = "${{ github.workspace }}\w_onemkl_p_2025.2.0.524_offline.exe"
          if (-not (Test-Path $mklInstaller)) {
            Write-Host "Downloading MKL installer..."
            Invoke-WebRequest -Uri "https://registrationcenter-download.intel.com/akdlm/IRC_NAS/47c7d946-fca1-441a-b0df-b094e3f045ea/w_onemkl_p_2025.2.0.524_offline.exe" -OutFile $mklInstaller
          }
          
          # Install MKL silently
          Write-Host "Installing MKL to $mklInstallDir..."
          Start-Process -FilePath $mklInstaller -ArgumentList "-s", "-a", "--silent", "--eula", "accept", "--install-dir", $mklInstallDir -Wait -NoNewWindow
          Write-Host "MKL installation complete"
        } else {
          Write-Host "MKL already installed"
        }
        
        # Set environment variables for CMake
        $mklRoot = "$mklInstallDir\mkl\latest"
        Write-Host "MKL_ROOT: $mklRoot"
        echo "MKLROOT=$mklRoot" >> $env:GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$mklRoot" >> $env:GITHUB_ENV