name: compile_mac

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_Mac_arm:
    runs-on: macos-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: recursive

    # Cache featomic
    - name: Cache featomic Build
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache-featomic-mac
      with:
        path: featomic/featomic_install
        key: featomic-arm-mac-${{ runner.os }}-${{ hashFiles('featomic/**') }}
        restore-keys: |
          featomic-arm-mac-${{ runner.os }}-
  
    - name: make_featomic
      if: steps.cache-featomic-arm-mac.outputs.cache-hit != 'true'
      run: |
          cd featomic/featomic 
          mkdir -p build 
          cd build 
          cmake -DCMAKE_BUILD_TYPE=Release -DFEATOMIC_FETCH_METATENSOR=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../../featomic_install_arm .. 
          make install
    
    - name: make_MacOS
      run: |
          cd Mac 
          make NoSpherA2_arm 
          mv NoSpherA2 ../NoSpherA2_Mac_arm

    - name: Archive executable
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: executable_MacOS_arm
        path: NoSpherA2_Mac_arm

  build_Mac_x86:
    runs-on: macos-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: recursive

    # Cache featomic
    - name: Cache featomic Build
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache-featomic-mac
      with:
        path: featomic/featomic_install
        key: featomic-x86-mac-${{ runner.os }}-${{ hashFiles('featomic/**') }}
        restore-keys: |
          featomic-x86-mac-${{ runner.os }}-

    - name: make_featomic_x86
      if: steps.cache-featomic-x86-mac.outputs.cache-hit != 'true'
      run: |
          rustup target add x86_64-apple-darwin 
          cd /Users/runner/work/NoSpherA2/NoSpherA2/featomic/featomic 
          mkdir -p build_x86_64 
          cd build_x86_64 
          cmake -DCMAKE_BUILD_TYPE=Release -DFEATOMIC_FETCH_METATENSOR=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../../featomic_install_x86 -DCMAKE_OSX_ARCHITECTURES=x86_64 .. 
          make install
    
    - name: make_MacOS
      run: |
          cd Mac 
          make NoSpherA2_x86 
          mv NoSpherA2 ../NoSpherA2_Mac_x86

    - name: Archive executable
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: executable_MacOS_x86
        path: NoSpherA2_Mac_x86

  combine_and_test:
    runs-on: macos-latest
    needs: [build_Mac_arm, build_Mac_x86]

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Download artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: executable_MacOS_arm
    - name: Download artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: executable_MacOS_x86
    - name: Combine artifacts
      run: |
        lipo -create -output NoSpherA2_Mac NoSpherA2_arm NoSpherA2_x86
    - name: Archive combined executable
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: NoSpherA2_Mac_combined  
        path: NoSpherA2_Mac
    - name: Test combined executable
      run: |
        chmod +x NoSpherA2_Mac
        cp NoSpherA2_Mac NoSpherA2
        make tests

        