name: CI Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: make
      run: cd Windows && msbuild NoSpherA2.sln -nologo -p:Configuration=Release
    - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executable_Windows
          path: |
            Windows/x64/Release/NoSpherA2.exe
