name: CI MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_MacOS
      run: brew install libomp && cd Mac && make && cp NoSpherA2 NoSpherA2_Mac
    - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executable_MacOS
          path: |
            Mac/NoSpherA2_Mac